### ISSUE TITLE
UAI: Sandbox Setup

### ISSUE THREAD

**Issue by Kathirvel-ai** [beckn/missions#149]
## Description

A Sandbox is required to act as a playground for the Network Participants. Any Network Participant who wants to onboard on the network should be able to test if their implementation is working correctly. So the Sandbox should support testing of participants either as a BAP or a BPP.
The implementation guide has been shared below for reference[Provide a brief description of the feature, including why it is needed and what it will accomplish. You can skip any of Goals, Expected Outcome, Implementation Details, Mockups / Wireframes if they are irrelevant. Please note that this section of the ticket is suggestive & you can structure it as per your prerogative.]

## Goals

- [ ] Capability for BAP to test advisory use case
- [ ] Capability for BPP to test advisory use case
- [ ] Capability for BAP to test Equipment Rental use case
- [ ] Capability for BPP to test Equipment Rental use case
- [ ] Capability for BAP to test Equipment/Agri Inputs Sales use case
- [ ] Capability for BPP to test Equipment/Agri Inputs Sales use case

## Expected Outcome

The Network Participant should be able to test for each use case as a BAP or a BPP 

## Implementation Guide MD Link

Guide link is [here](https://github.com/beckn/missions/tree/main/UAI)

### Domain

Agriculture

**Comment by yesrag2309** [comment]
**Current Status**

1. UAI Sandbox discussion call setup by today 2-2.30pm. Since @faizmagic was not available planning to schedule by 13th Nov

**Next Steps**

1. @Kathirvel-ai has to be ready for the call on the expectation what tech team has to deliver
2. UAI Sandbox discussion rescheduled to 13th Nov

@rajaneeshk90

**Comment by yesrag2309** [comment]
**Current Status**

UAI Sandbox discussion call setup by today but due to participants occupied in other calls couldn't make the discussion.

**Next Steps**

Planning to have the UAI Sandbox discussion tomorrow tech stand up call [UAI Sandbox ETA 18th Nov]

@faizmagic @Kathirvel-ai @emmayank @viraj89 @rajaneeshk90

**Comment by emmayank** [comment]
UAI Sandbox is live in BOC environment. attaching the postman collection[BOC.postman_collection.json](https://github.com/user-attachments/files/17800801/BOC.postman_collection.json)

**Comment by Kathirvel-ai** [comment]
Feedback: 

- The postman collection was provided on time. But Ankit was working on postman collection again on Tuesday (Day 1 of winroom) - seems like a communication gap
- One round of testing was required, as the troubleshooting was done in the call to see if the gateway, registry and the postman collection are working fine. 

Summary
- Sanity testing of the setup to be completed beforehand.
- All documentations to be shared with all the stakeholders at the start of the winroom
